name: hello-world
'on': push
jobs:
  docker_local_run:
    runs-on: self-hosted
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: list
       run: ls
     - name: Start containers
       run: docker-compose -f "docker-compose.yml" up -d --build
