name: hello-world
'on': push
jobs:
  docker_local_run:
    runs-on: self-hosted
    steps:
      - name: list images
        run: docker images
      - name: Checkout
        uses: action/checkout@v3
      - name: docker compose
        uses: ./docker-compose.yaml
      - name: list containers
        run: docker ps -a
      - name: remove container
        run: docker container rm hello
      - name: list containers
        run: docker ps -a
