name: hello-world
'on': push
jobs:
  docker_local_run:
    runs-on: self-hosted
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: List
       run: ls
     - name: Install compose
       run: docker pull aleksjej/armv7-docker-compose &&
            sudo chmod +x /usr/local/bin/docker-compose &&
            docker-compose --version
     - name: Remove old compose
       run: docker images &&
            docker ps -a
     - name: Start containers
       run: docker-compose -f docker-compose.yml up -d --build
