name: hello-world
'on': push
jobs:
  docker_local_run:
    runs-on: self-hosted
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: List
       run: ls
     - name: Compose
       run: docker compose up
