name: hello-world
'on': push
jobs:
  docker_local_run:
    runs-on: self-hosted
    steps:
      - name: list images
        run: docker images
      - name: Checkout
        uses: actions/checkout@v3
      - name: list containers
        run: docker ps -a
      - name: compose
        run: docker-compose up -d
