name: hello-world
'on': push
jobs:
  docker_local_run:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: list
        run: ls
      - name: compose
        run: docker-compose up -d
