name: hello-world
'on': push
jobs:
  docker_local_run:
    runs-on: self-hosted
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: List
       run: ls
     - name: Install compose
       run: docker pull aleksjej/armv7-docker-compose &&
            sudo chmod +x /usr/local/bin/docker-compose
     - name: Start containers
       run: docker run -f docker-compose.yml f39e30ccd182
