name: hello-world
'on': push
jobs:
  docker_local_run:
    runs-on: self-hosted
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: List
       run: ls
     - name: Install compose
       run:  sudo apt-get install docker-compose-plugin
     - name: check
       run:  docker ps
     - name: Start containers
       run: docker-compose -f "docker-compose.yml" up -d --build
